In [3]:
import torch

In [ ]:
# 1. 使用arrange创建一个行向量
x = torch.arange(12)  # 默认创建为整数,另外，除非额外指定，新创建好的张量都默认存储在内存中，并在CPU上计算
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [7]:
# 2. 通过张量的shape属性来访问张量的形状
x.shape

torch.Size([12])

In [8]:
# 3. 通过numel()来获取张量中元素的个数
x.numel()

12

In [9]:
# 4. 调用reshape函数，来改变张量的形状，但是不改变元素数量和值
X = x.reshape(3,4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [ ]:
# 5. 上边我们指定了是3行4列
#    如果，我们只关心3行，剩下一个维度的值可以填-1，这样他会自动计算出另外一个维度
X1 = x.reshape(3,-1) # 如果这个维度除不尽会报错
X1

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [ ]:
# 6. 获取一个全0张量
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [14]:
# 7. 获取一个全1矩阵
torch.ones((2,3))

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [15]:
# 8. 从特定的概率分布中随机采样得到张量中每个元素的值
# 从均值为0，标准差为1的标准正态分布中采样
torch.randn(3,4)

tensor([[ 1.2104,  1.1746, -0.8232,  0.3558],
        [-1.6643, -0.1207, -0.0082, -1.0191],
        [-0.1262, -1.8444,  0.2579,  1.3822]])

In [16]:
# 9. 通过提供包含数值的Python列表（或嵌套列表），来为所需张量中的每个元素赋予确定值
torch.tensor(
    [[2, 1, 4, 3], 
    [1, 2, 3, 4], 
    [4, 3, 2, 1]]
    )

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

In [ ]:
# 