### 2.1.1 入门

In [2]:
import torch

In [3]:
# 1. 使用arrange创建一个行向量
x = torch.arange(12)  # 默认创建为整数,另外，除非额外指定，新创建好的张量都默认存储在内存中，并在CPU上计算
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
# 2. 通过张量的shape属性来访问张量的形状(沿着每个轴的长度)
x.shape

torch.Size([12])

In [5]:
# 3. 通过numel()来获取张量中元素的个数
x.numel()

12

In [6]:
# 4. 调用reshape函数，来改变张量的形状，但是不改变元素数量和值。张量的大小也不会改变
X = x.reshape(3,4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [ ]:
# 5. 上边我们指定了是3行4列
#    如果，我们只关心3行，（而不关系有多少列，就是不想去手动计算有多少列），剩下一个维度的值可以填-1，这样他会自动计算出另外一个维度
X1 = x.reshape(3,-1) # 如果这个维度除不尽会报错
X2 = x.reshape(-1,4)
X1
X2

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [ ]:
# 6. 获取一个全0张量,形状为（2，3，4）
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
# 7. 获取一个全1矩阵，形状为（2，3）
torch.ones((2,3))

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
# 8. 从特定的概率分布中随机采样得到张量中每个元素的值
# 从均值为0，标准差为1的标准正态分布中随机采样
torch.randn(3,4)

tensor([[ 1.2104,  1.1746, -0.8232,  0.3558],
        [-1.6643, -0.1207, -0.0082, -1.0191],
        [-0.1262, -1.8444,  0.2579,  1.3822]])

In [ ]:
# 9. 通过提供包含数值的Python列表（或嵌套列表），来为所需张量中的每个元素赋予确定值
# 在这里，最外层的列表对应轴0，内层的列表对应轴1
torch.tensor(
    [[2, 1, 4, 3], 
    [1, 2, 3, 4], 
    [4, 3, 2, 1]]
    )

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

### 2.1.2. 运算符

对于任意具有相同形状的张量， 常见的标准算术运算符（+、-、*、/和**）都可以被升级为按元素运算，可以在同一形状的任意两个张量上调用按元素操作。

In [9]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x*y, x/y, x**y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [ ]:
torch.exp(torch.Tensor([0])) # 求e的x次方

tensor([1.])

In [13]:
# “按元素”方式可以应用更多的计算，包括像求幂这样的一元运算符。
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [ ]:
# 1. 对多个张量的连结
# 只需要提供张量列表，并给出沿哪个轴连结
# 沿行（轴-0，形状的第一个元素） 和按列（轴-1，形状的第二个元素）连结两个矩阵时的情况
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [15]:
# 2. 通过逻辑运算符构建张量
# 以X == Y为例： 
# 对于每个位置，如果X和Y在该位置相等，则新张量中相应项的值为1。 
# 这意味着逻辑语句X == Y在该位置处为真，否则该位置为0。
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [16]:
# 3. 对张量中所有元素求和，会得到一个单元素的张量
X.sum()

tensor(66.)

### 2.1.3. 广播机制

对于形状不同的两个张量，也可以通过调用广播机制来执行按孙苏操作。这种机制的工作方式如下：<br>
1. 通过适当复制元素来扩展一个或两个数组，以便在转换后，两个张量有相同的形状
2. 对生成的元素执行按元素操作

广播机制规则：<br>

- 如果遵守以下规则，则两个tensor是“可广播的”
    - 每个tensor至少有一个维度；
    - 遍历tensor所有维度时，从末尾随开始遍历，两个tensor存在下列情况：
        - tensor维度相等。
        - tensor维度不等且其中一个维度为1。
        - tensor维度不等且其中一个维度不存在。
- 如果两个tensor是“可广播的”，则计算过程遵循下列规则：
    - 如果两个tensor的维度不同，则在维度较小的tensor的前面增加维度，使它们维度相等。
    - 对于每个维度，计算结果的维度值取两个tensor中较大的那个值。
    - 两个tensor扩展维度的过程是将数值进行复制。

In [17]:
# 1. 在大多数情况下，沿着数组中长度为1的轴进行广播
a = torch.arange(3).reshape((3,1))
b = torch.arange(2).reshape((1,2))
a,b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [18]:
# 由于a和b分别是3*1和1*2矩阵，如果让它们相加，它们的形状不匹配。 
# 将两个矩阵广播为一个更大的矩阵，如下所示：矩阵a将复制列， 矩阵b将复制行，然后再按元素相加。

a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

### 2.1.4. 索引和切片

In [21]:
# 1. 使用[-1]来选择张量的最后一个元素
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
X,X[-1],X[1:3]

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [22]:
# 2. 可以通过指定索引来讲元素写入张量
X[1,2] = 9
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [23]:
# 3. 为多个元素赋值相同的值，只需要索引索引元素，然后为他们赋值
X[0:2,:] = 12  # 第0行和第一行，所有列
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

### 2.1.5. 节省内存
运行一些操作可能会导致为新结果分配内存。 例如，Y = X + Y，将取消引用Y指向的张量，而是指向新分配的内存处的张量。

In [ ]:
# 1. 使用id()函数来查看内存中引用对象的地址
before = id(Y)
Y = Y + X  # 这个操作是：Python首先计算Y + X，为结果分配新的内存，然后使Y指向内存中的这个新位置。
now = id(Y)
before, now, now==before

(139820810859056, 139820801527536, False)

可能这样做不是总是可取的，原因有：<br>
1. 我们不想总是不必要地分配内存，而是希望原地更新这些参数
2. 如果我们不原地更新这些参数，其他引用依然会指向旧的内存位置，可能导致某些代码会无意当中引用到旧的没有更新的参数

In [25]:
# 2. 使用切片表示法讲操作的结果分配给先前分配的数组，例如Y[:]=...
Z = torch.zeros_like(Y)  # 创建一个和Y形状相同的全0矩阵
print('ID(z)：',id(Z))
Z[:] = X + Y
print('ID(z)：',id(Z))

ID(z)： 139820801700208
ID(z)： 139820801700208


In [26]:
# 3. 如果在后续计算中没有重复使用X， 也可以使用X[:] = X + Y或X += Y来减少操作的内存开销。
before = id(X)
X += Y
id(X) == before

True

### 2.1.6. 转换为其他Python对象
将深度学习框架定义的张量转换为NumPy张量（ndarray）很容易，反之也同样容易。torch张量和numpy数组将共享它们的底层内存，就地操作更改一个张量也会同时更改另一个张量。

In [27]:
A = X.numpy()
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [28]:
# 1. 使用item()函数或其他Python内置函数将大小为1的张量转换为Python标量
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

### 2.1.7. 小结
深度学习存储和操作数据的主要接口是张量（n维数组）。它提供了各种功能，包括基本数学运算、广播、索引、切片、内存节省和转换其他Python对象。