# 数据操作

In [2]:
import torch

张量表示一个数值组成的数组，这个数组可能有多个维度

In [4]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

通过张量的 ·shape· 属性来访问张量的形状和张量中元素的总数

In [5]:
x.shape

torch.Size([12])

In [6]:
x.numel()

12

- 改变张量的形状，但是不改变他的元素数量和元素值，可以调用 `reshape` 函数

In [8]:
X = x.reshape(3, 4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [ ]:
import torch 

a = torch.tensor([[1,2],[3,4]])

a.type()

a = torch.tensor((2,3))
print(a.type())
a.size()

torch.ones((3,3), dtype=int)
torch.eye(2,dtype=int)


''' 随机 '''
a = torch.rand((2,3))
print(a)

b = torch.normal(mean=0, std=torch.rand(5))
print(b)

c = torch.Tensor(2,2).uniform_(-1,1)  # 均匀分布
print(c)


''' 序列 '''
d = torch.arange(0,11,2) # 起点，终点，步长
print(d)

e = torch.linspace(2,10,4) # 拿到等间隔的4个数字
print(e)

f = torch.randperm(10) # 生成从0-9的随机序列
print(f)

torch.LongTensor
tensor([[0.3981, 0.9664, 0.3181],
        [0.1224, 0.5975, 0.3656]])
tensor([-1.1451,  0.7077,  0.0092, -0.0138,  0.0045])
tensor([[ 0.2807, -0.2125],
        [-0.6219, -0.9944]])
tensor([ 0,  2,  4,  6,  8, 10])
tensor([ 2.0000,  4.6667,  7.3333, 10.0000])
tensor([3, 8, 1, 6, 5, 0, 2, 4, 9, 7])
